package com.luoke.hid.reports

object DescriptorCollection {
    private fun b(i: Int) = i.toByte()

    val MOUSE_KEYBOARD_COMBO = byteArrayOf(
        // ── Mouse ──
        b(0x05), b(0x01),                         // USAGE_PAGE (Generic Desktop)
        b(0x09), b(0x02),                         // USAGE (Mouse)
        b(0xa1), b(0x01),                         // COLLECTION (Application)
        b(0x05), b(0x01),                         //   USAGE_PAGE (Generic Desktop)
        b(0x09), b(0x02),                         //   USAGE (Mouse)
        b(0xa1), b(0x02),                         //   COLLECTION (Logical)
        b(0x85), b(0x04),                         //     REPORT_ID (Mouse=4)
        b(0x09), b(0x01),                         //     USAGE (Pointer)
        b(0xa1), b(0x00),                         //     COLLECTION (Physical)
        b(0x05), b(0x09),                         //       USAGE_PAGE (Button)
        b(0x19), b(0x01),                         //       USAGE_MINIMUM (Button 1)
        b(0x29), b(0x03),                         //       USAGE_MAXIMUM (Button 3)
        b(0x15), b(0x00),                         //       LOGICAL_MINIMUM (0)
        b(0x25), b(0x01),                         //       LOGICAL_MAXIMUM (1)
        b(0x75), b(0x01),                         //       REPORT_SIZE (1)
        b(0x95), b(0x03),                         //       REPORT_COUNT (3)
        b(0x81), b(0x02),                         //       INPUT (Data,Var,Abs)
        b(0x95), b(0x01),                         //       REPORT_COUNT (1)
        b(0x75), b(0x05),                         //       REPORT_SIZE (5)
        b(0x81), b(0x03),                         //       INPUT (Cnst,Var,Abs)
        b(0x05), b(0x01),                         //       USAGE_PAGE (Generic Desktop)
        b(0x09), b(0x30),                         //       USAGE (X)
        b(0x09), b(0x31),                         //       USAGE (Y)
        b(0x16), b(0x01), b(0xf8),                //       LOGICAL_MINIMUM (-2047)
        b(0x26), b(0xff), b(0x07),                //       LOGICAL_MAXIMUM (2047)
        b(0x75), b(0x10),                         //       REPORT_SIZE (16)
        b(0x95), b(0x02),                         //       REPORT_COUNT (2)
        b(0x81), b(0x06),                         //       INPUT (Data,Var,Rel)
        b(0x09), b(0x38),                         //       USAGE (Wheel)
        b(0x15), b(0x81),                         //       LOGICAL_MINIMUM (-127)
        b(0x25), b(0x7f),                         //       LOGICAL_MAXIMUM (127)
        b(0x75), b(0x08),                         //       REPORT_SIZE (8)
        b(0x95), b(0x01),                         //       REPORT_COUNT (1)
        b(0x81), b(0x06),                         //       INPUT (Data,Var,Rel)
        b(0x05), b(0x0c),                         //       USAGE_PAGE (Consumer)
        b(0x0a), b(0x38), b(0x02),                //       USAGE (AC Pan)
        b(0x15), b(0x81),                         //       LOGICAL_MINIMUM (-127)
        b(0x25), b(0x7f),                         //       LOGICAL_MAXIMUM (127)
        b(0x75), b(0x08),                         //       REPORT_SIZE (8)
        b(0x95), b(0x01),                         //       REPORT_COUNT (1)
        b(0x81), b(0x06),                         //       INPUT (Data,Var,Rel)
        b(0xc0),                                  //     END_COLLECTION
        b(0xc0),                                  //   END_COLLECTION
        b(0xc0),                                  // END_COLLECTION

        // ── Keyboard ──
        b(0x05), b(0x01),                         // USAGE_PAGE (Generic Desktop)
        b(0x09), b(0x06),                         // USAGE (Keyboard)
        b(0xa1), b(0x01),                         // COLLECTION (Application)
        b(0x85), b(0x08),                         //   REPORT_ID (Keyboard=8)
        b(0x05), b(0x07),                         //   USAGE_PAGE (Key Codes)
        b(0x19), b(0xe0),                         //   USAGE_MINIMUM (224)
        b(0x29), b(0xe7),                         //   USAGE_MAXIMUM (231)
        b(0x15), b(0x00),                         //   LOGICAL_MINIMUM (0)
        b(0x25), b(0x01),                         //   LOGICAL_MAXIMUM (1)
        b(0x75), b(0x01),                         //   REPORT_SIZE (1)
        b(0x95), b(0x08),                         //   REPORT_COUNT (8)
        b(0x81), b(0x02),                         //   INPUT (Data,Var,Abs)
        b(0x95), b(0x01),                         //   REPORT_COUNT (1)
        b(0x75), b(0x08),                         //   REPORT_SIZE (8)
        b(0x81), b(0x01),                         //   INPUT (Const)
        b(0x95), b(0x01),                         //   REPORT_COUNT (1)
        b(0x75), b(0x08),                         //   REPORT_SIZE (8)
        b(0x15), b(0x00),                         //   LOGICAL_MINIMUM (0)
        b(0x25), b(0x65),                         //   LOGICAL_MAXIMUM (101)
        b(0x05), b(0x07),                         //   USAGE_PAGE (Key codes)
        b(0x19), b(0x00),                         //   USAGE_MINIMUM (0)
        b(0x29), b(0x65),                         //   USAGE_MAXIMUM (101)
        b(0x81), b(0x00),                         //   INPUT (Data,Array)
        b(0xc0)                                   // END_COLLECTION
    )
}
