package com.luoke.hid.reports

object DescriptorCollection {
    val MOUSE_KEYBOARD_COMBO = byteArrayOf(
        // ── Mouse ──
        0x05, 0x01,                         // USAGE_PAGE (Generic Desktop)
        0x09, 0x02,                         // USAGE (Mouse)
        0xa1, 0x01,                         // COLLECTION (Application)
        0x05, 0x01,                         //   USAGE_PAGE (Generic Desktop)
        0x09, 0x02,                         //   USAGE (Mouse)
        0xa1, 0x02,                         //   COLLECTION (Logical)
        0x85, 0x04,                         //     REPORT_ID (Mouse=4)
        0x09, 0x01,                         //     USAGE (Pointer)
        0xa1, 0x00,                         //     COLLECTION (Physical)
        0x05, 0x09,                         //       USAGE_PAGE (Button)
        0x19, 0x01,                         //       USAGE_MINIMUM (Button 1)
        0x29, 0x03,                         //       USAGE_MAXIMUM (Button 3)
        0x15, 0x00,                         //       LOGICAL_MINIMUM (0)
        0x25, 0x01,                         //       LOGICAL_MAXIMUM (1)
        0x75, 0x01,                         //       REPORT_SIZE (1)
        0x95, 0x03,                         //       REPORT_COUNT (3)
        0x81, 0x02,                         //       INPUT (Data,Var,Abs)
        0x95, 0x01,                         //       REPORT_COUNT (1)
        0x75, 0x05,                         //       REPORT_SIZE (5)
        0x81, 0x03,                         //       INPUT (Cnst,Var,Abs)
        0x05, 0x01,                         //       USAGE_PAGE (Generic Desktop)
        0x09, 0x30,                         //       USAGE (X)
        0x09, 0x31,                         //       USAGE (Y)
        0x16, 0x01, 0xf8.toByte(),          //       LOGICAL_MINIMUM (-2047)
        0x26, 0xff.toByte(), 0x07,          //       LOGICAL_MAXIMUM (2047)
        0x75, 0x10,                         //       REPORT_SIZE (16)
        0x95, 0x02,                         //       REPORT_COUNT (2)
        0x81, 0x06,                         //       INPUT (Data,Var,Rel)
        0x09, 0x38,                         //       USAGE (Wheel)
        0x15, 0x81.toByte(),                //       LOGICAL_MINIMUM (-127)
        0x25, 0x7f,                         //       LOGICAL_MAXIMUM (127)
        0x75, 0x08,                         //       REPORT_SIZE (8)
        0x95, 0x01,                         //       REPORT_COUNT (1)
        0x81, 0x06,                         //       INPUT (Data,Var,Rel)
        0x05, 0x0c,                         //       USAGE_PAGE (Consumer)
        0x0a, 0x38, 0x02,                   //       USAGE (AC Pan)
        0x15, 0x81.toByte(),                //       LOGICAL_MINIMUM (-127)
        0x25, 0x7f,                         //       LOGICAL_MAXIMUM (127)
        0x75, 0x08,                         //       REPORT_SIZE (8)
        0x95, 0x01,                         //       REPORT_COUNT (1)
        0x81, 0x06,                         //       INPUT (Data,Var,Rel)
        0xc0,                               //     END_COLLECTION
        0xc0,                               //   END_COLLECTION
        0xc0,                               // END_COLLECTION

        // ── Keyboard ──
        0x05, 0x01,                         // USAGE_PAGE (Generic Desktop)
        0x09, 0x06,                         // USAGE (Keyboard)
        0xa1, 0x01,                         // COLLECTION (Application)
        0x85, 0x08,                         //   REPORT_ID (Keyboard=8)
        0x05, 0x07,                         //   USAGE_PAGE (Key Codes)
        0x19, 0xe0,                         //   USAGE_MINIMUM (224)
        0x29, 0xe7,                         //   USAGE_MAXIMUM (231)
        0x15, 0x00,                         //   LOGICAL_MINIMUM (0)
        0x25, 0x01,                         //   LOGICAL_MAXIMUM (1)
        0x75, 0x01,                         //   REPORT_SIZE (1)
        0x95, 0x08,                         //   REPORT_COUNT (8)
        0x81, 0x02,                         //   INPUT (Data,Var,Abs)
        0x95, 0x01,                         //   REPORT_COUNT (1)
        0x75, 0x08,                         //   REPORT_SIZE (8)
        0x81, 0x01,                         //   INPUT (Const)
        0x95, 0x01,                         //   REPORT_COUNT (1)
        0x75, 0x08,                         //   REPORT_SIZE (8)
        0x15, 0x00,                         //   LOGICAL_MINIMUM (0)
        0x25, 0x65,                         //   LOGICAL_MAXIMUM (101)
        0x05, 0x07,                         //   USAGE_PAGE (Key codes)
        0x19, 0x00,                         //   USAGE_MINIMUM (0)
        0x29, 0x65,                         //   USAGE_MAXIMUM (101)
        0x81, 0x00,                         //   INPUT (Data,Array)
        0xc0                                // END_COLLECTION
    )
}
